repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    - id: flake8
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
    -   id: mypy
        verbose: false
        entry: bash -c 'mypy "$@" || true' --
#        args: [-p msn_cli]
-   repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
    -   id: isort
-   repo: https://github.com/jorisroovers/gitlint
    rev:  main
    hooks:
    -   id: gitlint
